# Generated by Django 3.1.5 on 2021-01-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.TextField(default='Full_Name')),
                ('Email', models.EmailField(default='email@gmail.com', max_length=254)),
                ('Username', models.TextField(default='Username')),
                ('Password', models.TextField(default='Password')),
                ('Location', models.CharField(default='Location', max_length=100)),
                ('PhoneNumber', models.CharField(default='PhoneNumber', max_length=100)),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=100)),
                ('Bloodgroup', models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='', max_length=100)),
                ('Image', models.ImageField(default='Health_Professional/dummy.jpg', upload_to='Signup/')),
                ('Sender_ID', models.TextField(default='Sender_ID')),
                ('Device_type', models.CharField(choices=[('ios', 'ios'), ('android', 'android'), ('web', 'web')], default='android', max_length=100)),
                ('latitude', models.CharField(default='latitude', max_length=100)),
                ('longitude', models.CharField(default='longitude', max_length=100)),
            ],
        ),
    ]
