# Generated by Django 3.1.5 on 2021-01-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20210124_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_blood',
            name='Place_to_Donate',
        ),
        migrations.AlterField(
            model_name='request_blood',
            name='Blood_for',
            field=models.CharField(default='self', max_length=100),
        ),
    ]
