# Generated by Django 3.1.5 on 2021-01-25 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20210125_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_blood',
            name='Donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.donate_blood'),
        ),
    ]
