# Generated by Django 3.1.5 on 2021-01-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_request_blood_donor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate_blood',
            old_name='Status',
            new_name='Donate_Blood_Status',
        ),
        migrations.RenameField(
            model_name='request_blood',
            old_name='Status',
            new_name='Request_Blood_Status',
        ),
    ]
